[dev]
  command = "npm run vite:start"
  publish = "dist"
  

[build]
  command = "npm run vite:build"
  publish = "dist"


[[redirects]]
  from = "/api/books"
  to = "/.netlify/functions/books"
  status = 200